title: Scott W. H. Young
navbar_title: Scott W. H. Young 

author:
  name: Scott W. H. Young 
  email: # contact email

description: Hi. Iâ€™m Scott, a librarian and associate professor at Montana State University. My work focuses on library user experience, values-based assessment, participatory design, privacy, and ethics. # description of your site

url: "https://www.scottwhyoung.com" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # The subpath of your site, e.g. /blog

jekyllacademic:
  homepage_title: "User Experience & Assessment Librarian" # Your homepage title
  disqusname: # Your disqus sitename
  footer: Site content licensed CC BY #
  contentlicense: "CC BY 4.0" # Choose either one of these to put: MIT, Commons Clause, CC BY 4.0, CC BY-NC 4.0, CC BY-ND 4.0, CC BY-NC-ND 4.0, CC BY-NC-SA 4.0, CC BY-NC-SA 4.0, CC BY-SA 4.0
  socials:
    twitter:  # Your twitter username
    github:  # Your github username
    linkedin:  # Your linkedin
    keybase:  # Your keybase

# No need to edit this part, however if you want to, that's fine as well

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /posts/:slug
  projects:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
